---
title: "Post Hoc Power Analysis"
execute:
  echo: false
---

## Setup

```{r}
#| label: setup
#| include: false

library(here)
source(here("Scripts", "DataAppendixScripts", "helpers.R"))
source(here("Scripts", "DataAppendixScripts", "models.R"))

```

```{r}
#| label: load-realdata

url_data <- "https://data.mendeley.com/datasets/rdky78bk8r/2/files/b58a7054-4978-4239-81db-00f9efd86e44/WHOQOL_Data.dat"
realdata <- read.table(url_data)

url_labels <- "https://data.mendeley.com/datasets/rdky78bk8r/2/files/ae2a5c01-2fc2-43e5-b31c-8db8cc5bff8a/WHOQOL_Labels.txt"
column_labels <- read.table(url_labels)
column_labels <- column_labels$V1
names(realdata) <- gsub("_[FPSA]$", "", column_labels)

n_real <- nrow(realdata) # Sample size of the real data

df_model <- semPower::semPower.getDf(analyzemodel) # Degrees of freedom for the model, needed for semPower post hoc
```

## Post hoc power analysis

### With simulation

- Passo 1: Ajustar o modelo aos dados reais

```{r}
#| label: realdata-model

fit_real <- cfa(
  analyzemodel,
  data = realdata,
  estimator = "mlr"
)
```

- Passo 2: Simular modelo nulo com N real

```{r}
#| label: sim-null-posthoc

realmodel_null <- sim(
    nRep      = 1000,
    n         = n_real,
    analyzemodel,
    generate  = fit_real,
    std.lv    = TRUE,
    lavaanfun = "cfa",
    estimator = "mlr",
    seed      = SEED,
    multicore = TRUE
)
```

- Passo 3: Simular modelo alternativo com N real

```{r}
#| label: sim-alt-posthoc

h1model_alt <- sim(
    nRep      = 1000,
    n         = n_real,
    analyzemodel,
    generate  = h1model,
    std.lv    = TRUE,
    lavaanfun = "cfa",
    estimator = "mlr",
    seed      = SEED,
    multicore = TRUE
)
```

- Passo 4: Poder no N coletado

```{r}
#| label: fig-posthoc-plotpower
#| fig-cap: "Power curve for post hoc analysis based on simulation."
#| fig-width: 8
#| fig-height: 5

plotPowerFit(
    h1model_alt,
    nullObject = realmodel_null,
    alpha      = ALPHA,
    usedFit    = FITS
)
```

```{r}
#| label: tbl-posthoc-power
#| tbl-cap: "Power for post hoc analysis based on simulation."

getPowerFit(
    h1model_alt,
    nullObject = realmodel_null,
    alpha      = ALPHA,
    usedFit    = FITS
)
```


### With semPower

```{r}
#| label: fig-posthoc-rsmea
#| fig-cap: "Post hoc power analysis for RMSEA."
#| fig-width: 8
#| fig-height: 5

ph_rsmea <- semPower::semPower.postHoc(
    effect         = 0.05,
    effect.measure = "RMSEA", # RMSEA under H1 (exact-fit model: H0: RMSEA = 0)
    alpha          = ALPHA,
    N              = n_real,
    df             = df_model,
    p              = P # Just for GFI and AGFI
)

summary(ph_rsmea)
```

```{r}
#| label: fig-posthoc-realmodel
#| fig-cap: "Post hoc power analysis for the real model."
#| fig-width: 8
#| fig-height: 5

ph_realmodel <- semPower.powerLav(
  type = 'post-hoc',
  alpha = ALPHA,
  N = n_real,
  modelPop = popmodel,
  modelH0 = fit_real,
)

summary(ph_realmodel)
```

```{r}
#| label: fig-posthoc-miss
#| fig-cap: "Post hoc power analysis for the misspecified model."
#| fig-width: 8
#| fig-height: 5

ph_posthoc_miss <- semPower.powerLav(
  type = 'post-hoc',
  alpha = ALPHA,
  N = n_real,
  modelPop = popmodel,
  modelH0 = fit_real,
  modelH1 = h1modelfree
)

summary(ph_posthoc_miss)
```

